---
tower_inventories:
  - name: Workshop Inventory
    organization: Default

  - name: AWS Inventory - Development
    organization: Default

tower_inventory_sources:
  - name: satellite_source
    inventory: Workshop Inventory
    credential: Inventory Credential
    source: satellite6
    update_on_launch: false
    overwrite: true
    source_vars:
      keyed_groups:
        - prefix: env
          key: foreman_content_facet_attributes.lifecycle_environment_name
        - prefix: cv
          key: foreman_content_facet_attributes.content_view_name
        - prefix: os
          key: foreman_operatingsystem_name

  - name: EC2 Dynamic Source - Development
    inventory: AWS Inventory - Development
    source: ec2
    source_vars: "{{ hostvars['ansible-1.example.com']['dynamic_development_source_vars'] }}"
#      regions:
#        - us-east-1
#      filters:
#        tag:Environment: Dev
#        instance-state-name : running
#      hostnames:
#        - tag:Name
#        - private-dns-name
#      keyed_groups:
#        - prefix: Env
#          key: tags['Environment']
#       - prefix: AnsibleGroup
#          key: tags['AnsibleGroup']
#      compose:
#        ansible_host: private_ip_address
    overwrite: true
    update_on_launch: true
    update_cache_timeout: 0
