---
- hosts: "{{ rhel_nodes }}"
  become: false
  tasks:
  - name: Interrogate one RHEL node to get requisite files for convert2rhel requirements
    block:
      - name: verify operating system
        assert:
          that: "ansible_distribution == 'RedHat'"

      - find: paths="/etc/pki/entitlement" recurse=yes patterns="*.pem"
        register: entitlement_certs

      #- include: c2r_subtasks.yml full_file_path={{ item.path }}
      #  with_items:
      #  - "{{ entitlement_certs.files }}"
      - set_fact:
          entitlement_certs_files: "{{ entitlement_certs.files }}"

      - debug:
          msg: "entitlement_certs_files ==> {{ entitlement_certs_files | map(attribute='path') | list }}"

      - name: Slurp "{{ item }}" from rhel node to control
      #- include: c2r_subtasks.yml full_file_path={{ item }}
        slurp: src="{{ item }}"
        register: slurped_files
        with_items:
        - "/etc/pki/rpm-gpg/RPM-GPG-KEY-redhat-release"
        - "/etc/yum.repos.d/redhat.repo"
        - "{{ entitlement_certs_files | map(attribute='path') | list }}"

      # This provides dict of slurped files
      #- debug:
      #    msg: "{{ slurped_files.results }}"

      - debug:
          msg:
            - "{{ item['source'][*] }}"
          #msg: "{{ item['content'] | b64decode }}"
        with_items: "{{ slurped_files['results'] }}" 

  run_once: yes

- hosts: "{{ centos_nodes }}"
  become: true
  tasks:
  - name: verify operating system
    assert:
      that: "ansible_distribution == 'CentOS'"

  - name: stat redhat.repo
    stat: path=/etc/yum.repos.d/redhat.repo
    register: redhat_repofile_stat

  - name: Move redhat.repo to centos.repo
    command: mv /etc/yum.repos.d/redhat.repo /etc/yum.repos.d/centos.repo
    when: redhat_repofile_stat.stat.exists

  - name: Copy "{{ item }}" from control to centos node
    #copy: src="{{ temp_transfer_01.path }}/{{ item }}" dest="{{ item }}"
    copy: src="{{ item }}" dest="{{ item }}"
    with_items:
    - "/etc/pki/rpm-gpg/RPM-GPG-KEY-redhat-release"
    - "/etc/yum.repos.d/redhat.repo"

  - name: Copy "{{ item.path }}" from control to centos node
    #copy: src="{{ temp_transfer_01.path }}/{{ item.path }}" dest="{{ item.path }}"
    copy: src="{{ item.path }}" dest="{{ item.path }}"
    with_items:
    - "{{ entitlement_certs.files }}"

  - name: Ensure "{{ item.path }}" is immutable
    file:
      path: "{{ item.path }}"
      attr: +i
    with_items:
    - "{{ entitlement_certs.files }}"
    register: cert_file
    changed_when: "'i' not in cert_file.diff.before.attributes"
