---
- hosts: all
  tasks:
  - name: Randomized startup delay...
    command: /bin/sleep "{{ 10 | random }}"
    delegate_to: localhost
    connection: local
    async: 45
    poll: 0

- hosts: all
  tasks:
  - debug:
