---
- hosts: "{{ HOSTS | default('satellite.example.com') }}"
  connection: local
  vars:
    organization: "Default Organization"
    validate_certs: false
  tasks:
  - name: Get all existing hosts resource_info for org "Default Organization"
    theforeman.foreman.resource_info:
      # resource: activation_keys
      resource: hosts
      # organization: ACME
    register: resource_info_hosts_result

  - debug:
      # | to_json | from_json ...is workaround found here...
      # https://stackoverflow.com/questions/44546154/jmespathtypeerror-when-using-json-query-filter-in-ansible-with-starts-with
      msg: "{{ resource_info_hosts_result | to_json | from_json | json_query(ansible_host_name_query) }}"
    vars:
      ansible_host_name_query: "resources[?starts_with(name, 'node')].name"
      # this also works...
      # ansible_host_name_query: "resources[?starts_with(name, 'node') == `true`].name"

  - name: "Get instance details"
    import_role:
      name: ec2_node_tools
      tasks_from: get_instance_details
  # If you comment out the below vars, you can pass them as Tower job template extra vars    
  # vars:
  #   instances:
  #     tags:
  #       short_name: 'node*'
  #       guid: 'test01'
  #       Student: 'student1'

  - name: "Set facts to split"
    set_fact:
      ansible_lifecycle_env: "{{ resource_info_hosts_result | to_json | from_json | json_query(ansible_specific_host_name_le_query) }}"
    vars:
      ansible_host_name_query: "resources[?starts_with(name, 'node')].name"
      ansible_specific_host_name_le_query: "resources[?contains(['{{ item }}'], name)].content_facet_attributes.lifecycle_environment_name | [0]"
    with_items: "{{ resource_info_hosts_result | to_json | from_json | json_query(ansible_host_name_query) | list }}"
    when: instances_details is not none

  - debug:
      msg:
        - "Instance ID ==> {{ instances_details | json_query(ansible_instance_id_query) }}"
        - "Node ==> {{ item }}"
        - "LE   ==> {{ resource_info_hosts_result | to_json | from_json | json_query(ansible_specific_host_name_le_query) }}"
        - "CV   ==> {{ resource_info_hosts_result | to_json | from_json | json_query(ansible_specific_host_name_cv_query) }}"
        - "OS   ==> {{ resource_info_hosts_result | to_json | from_json | json_query(ansible_specific_host_name_os_query) | replace('.','_') | replace(' ','_') }}"
        - "Env  ==> {{ ansible_lifecycle_env.split('_')[1] }}"
        - "Distro > {{ resource_info_hosts_result | to_json | from_json | json_query(ansible_specific_host_name_os_query) | replace('.','_') | replace(' ','_') }}"
    vars:
      ansible_host_name_query: "resources[?starts_with(name, 'node')].name"
      ansible_specific_host_name_le_query: "resources[?contains(['{{ item }}'], name)].content_facet_attributes.lifecycle_environment_name | [0]"
      ansible_specific_host_name_cv_query: "resources[?contains(['{{ item }}'], name)].content_facet_attributes.content_view_name | [0]"
      ansible_specific_host_name_os_query: "resources[?contains(['{{ item }}'], name)].operatingsystem_name | [0]"
      ansible_instance_id_query: "instances[?contains(['{{ item.split('.')[0] | lower }}'], tags.short_name)].instance_id | [0]"
    with_items: "{{ resource_info_hosts_result | to_json | from_json | json_query(ansible_host_name_query) | list }}"
    when: instances_details is not none
