---
- hosts: "{{ HOSTS | default('satellite.example.com') }}"
  connection: local
  vars:
    organization: "Default Organization"
    validate_certs: false
  tasks:
  - name: Get all existing hosts resource_info for org "Default Organization"
    theforeman.foreman.resource_info:
      resource: hosts
    register: resource_info_hosts_result

  - debug:
      msg: "{{ resource_info_hosts_result | to_json | from_json | json_query(ansible_host_name_query) }}"
    vars:
      ansible_host_name_query: "resources[?starts_with(name, 'node')].name"

  - name: "Get instance details"
    import_role:
      name: ec2_node_tools
      tasks_from: get_instance_details

  - name: Populate requisite instance tags that reflect current Satellite LE, CV, OS state
    vars:
      ansible_host_name_query: "resources[?starts_with(name, 'node')].name"
      ansible_specific_host_name_le_query: "resources[?contains(['{{ item }}'], name)].content_facet_attributes.lifecycle_environment_name | [0]"
      ansible_specific_host_name_cv_query: "resources[?contains(['{{ item }}'], name)].content_facet_attributes.content_view_name | [0]"
      ansible_specific_host_name_os_query: "resources[?contains(['{{ item }}'], name)].operatingsystem_name | [0]"
      ansible_instance_id_query: "instances[?contains(['{{ item.split('.')[0] | lower }}'], tags.short_name)].instance_id | [0]"
    ec2_tag:
      region: "{{ ec2_region }}"
      resource: "{{ instances_details | json_query(ansible_instance_id_query) }}"
      state: present
      tags:
        Environment: "{{ resource_info_hosts_result | to_json | from_json | json_query(ansible_specific_host_name_le_query) }}"
        ContentView: "{{ resource_info_hosts_result | to_json | from_json | json_query(ansible_specific_host_name_cv_query) }}"
        Distro: "{{ resource_info_hosts_result | to_json | from_json | json_query(ansible_specific_host_name_os_query) | replace('.','_') | replace(' ','_') }}"
    with_items: "{{ resource_info_hosts_result | to_json | from_json | json_query(ansible_host_name_query) | list }}"
    when: instances_details is not none

  - debug:
      msg:
        - "Instance ID ==> {{ instances_details | json_query(ansible_instance_id_query) }}"
        - "Node ==> {{ item }}"
        - "LE   ==> {{ resource_info_hosts_result | to_json | from_json | json_query(ansible_specific_host_name_le_query) }}"
        - "CV   ==> {{ resource_info_hosts_result | to_json | from_json | json_query(ansible_specific_host_name_cv_query) }}"
        - "OS   ==> {{ resource_info_hosts_result | to_json | from_json | json_query(ansible_specific_host_name_os_query) | replace('.','_') | replace(' ','_') }}"
    when: instances_details is not none
