---
- hosts: all
  gather_facts: no
  tasks:
  - name: Dynamically add ansible-1.example.com to inventory
    add_host:
      name: ansible-1.example.com

- hosts: ansible-1.example.com
  connection: local
  gather_facts: no
  vars:
    organization: "Default Organization"
    validate_certs: false
  tasks:
  - set_fact:
      node_group: "env_{{ centos_lifecycle_environment }}"
  - name: Transfer hosts in Satellite LE "{{ node_group }}" to LE "{{ rhel_lifecycle_environment }}"
    theforeman.foreman.host:
      name: "{{ item }}"
      lifecycle_environment: "{{ rhel_lifecycle_environment }}"
      content_view: "{{ rhel_lifecycle_environment.split('_')[0] }}"
    with_items: "{{ groups[node_group] }}"
    register: transfer_hosts_result
  - debug:
      var: transfer_hosts_result
