---
- hosts: "{{ HOSTS | default('control[0]') }}"
  connection: local
  vars:
    tower_infra_workloads:
      - redhat_cop.tower_configuration.inventories
      - redhat_cop.tower_configuration.inventory_sources
      - redhat_cop.tower_configuration.job_templates
      - redhat_cop.tower_configuration.projects
    #tower_hostname: "{{ lookup('env', 'TOWER_HOST') }}"
    tower_hostname: "{{ hostvars[inventory_hostname].ansible_fqdn }}"
    tower_validate_certs: false

  tasks:
    - name: Slurp dynamic_development_source_vars.yaml
      slurp: src=files/dynamic_development_source_vars.yaml
      register: dynamic_development_source_vars_slurped

    - set_fact:
        dynamic_development_source_vars: "{{ dynamic_development_source_vars_slurped['content'] | b64decode }}"

    - debug:
        var: "{{ dynamic_development_source_vars }}"   
    - name: deploy tower_infra workloads
      include_role:
        name: "{{ tower_infra_vars }}"
      loop: "{{ tower_infra_workloads }}"
      loop_control:
        loop_var: tower_infra_vars
