---
- hosts: "{{ HOSTS | default('control[0]') }}"
#- hosts: "{{ HOSTS | default('ansible-1.example.com') }}"
  connection: local
  collections:
    - awx.awx
  vars:
    tower_hostname: "{{ hostvars[inventory_hostname].ansible_host }}"
    tower_validate_certs: false

  tasks:
  - name: Update inventory via source ==> EC2 Dynamic Source - "{{ env_inventory }}" Development
    tower_inventory_source_update:
      name: "EC2 Dynamic Source - {{ env_inventory }} Development"
      inventory: "{{ env_inventory }} Development"
      organization: Default

  - name: Update inventory via source ==> inventory_{{ env_inventory | lower }}_dev.aws_ec2
    tower_inventory_source_update:
      name: "inventory_{{ env_inventory | lower }}_dev.aws_ec2"
      inventory: "ALL Development"
      organization: Default
