---
- hosts: "{{ HOSTS | default('control[0]') }}"
#- hosts: "{{ HOSTS | default('ansible-1.example.com') }}"
  connection: local
  collections:
    - awx.awx
  vars:
    tower_hostname: "{{ hostvars[inventory_hostname].ansible_host }}"
    tower_validate_certs: false

  tasks:
  - name: Update a single inventory source
    tower_inventory_source_update:
      name: "satellite_source"
      inventory: "Workshop Inventory"
      organization: Default
